# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://eduanbekker.com/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
#copyright = "Copyright © 2023, Eduan Bekker; all rights reserved."
# canonifyurls = true
paginate = 10
theme = ["github.com/chipzoller/hugo-clarity"]
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
enforceDarkMode = true
